/**
 * importConstants
 *
 * @subpackage             fixture Constants
 * @category               Constants
 * @DateOfCreation         22 May 2018
 * @ShortDescription       This is responsible for first Constants action names
 */
export const clinicSlotConstants = {

    //CLINIC_SLOT_
    CLINIC_SLOT_REQUEST     : 'CLINIC_SLOT_REQUEST',
    CLINIC_SLOT_SUCCESS     : 'CLINIC_SLOT_SUCCESS',
    CLINIC_SLOT_FAILURE     : 'CLINIC_SLOT_FAILURE',

    //SAVE_CLINIC_SLOT_
    SAVE_CLINIC_SLOT_REQUEST     : 'SAVE_CLINIC_SLOT_REQUEST',
    SAVE_CLINIC_SLOT_SUCCESS     : 'SAVE_CLINIC_SLOT_SUCCESS',
    SAVE_CLINIC_SLOT_FAILURE     : 'SAVE_CLINIC_SLOT_FAILURE',

    //GET_CLINIC_SLOT
    GET_CLINIC_SLOT_REQUEST     : 'GET_CLINIC_SLOT_REQUEST',
    GET_CLINIC_SLOT_SUCCESS     : 'GET_CLINIC_SLOT_SUCCESS',
    GET_CLINIC_SLOT_FAILURE     : 'GET_CLINIC_SLOT_FAILURE',

    //GET_CLINIC_SLOT_MANAGE
    GET_CLINIC_SLOT_MANAGE_REQUEST     : 'GET_CLINIC_SLOT_MANAGE_REQUEST',
    GET_CLINIC_SLOT_MANAGE_SUCCESS     : 'GET_CLINIC_SLOT_MANAGE_SUCCESS',
    GET_CLINIC_SLOT_MANAGE_FAILURE     : 'GET_CLINIC_SLOT_MANAGE_FAILURE',

    //GET_CLINIC_SLOT_DATE
    GET_CLINIC_SLOT_DATE_REQUEST     : 'GET_CLINIC_SLOT_DATE_REQUEST',
    GET_CLINIC_SLOT_DATE_SUCCESS     : 'GET_CLINIC_SLOT_DATE_SUCCESS',
    GET_CLINIC_SLOT_DATE_FAILURE     : 'GET_CLINIC_SLOT_DATE_FAILURE',

    //DELETE_CLINIC_SLOT
    DELETE_CLINIC_SLOT_REQUEST     : 'DELETE_CLINIC_SLOT_REQUEST',
    DELETE_CLINIC_SLOT_SUCCESS     : 'DELETE_CLINIC_SLOT_SUCCESS',
    DELETE_CLINIC_SLOT_FAILURE     : 'DELETE_CLINIC_SLOT_FAILURE',

    //STATUS_CLINIC_SLOT
    STATUS_CLINIC_SLOT_REQUEST     : 'STATUS_CLINIC_SLOT_REQUEST',
    STATUS_CLINIC_SLOT_SUCCESS     : 'STATUS_CLINIC_SLOT_SUCCESS',
    STATUS_CLINIC_SLOT_FAILURE     : 'STATUS_CLINIC_SLOT_FAILURE',

    //STATUS_CLINIC_TIME_SLOT
    STATUS_CLINIC_TIME_SLOT_REQUEST     : 'STATUS_CLINIC_TIME_SLOT_REQUEST',
    STATUS_CLINIC_TIME_SLOT_SUCCESS     : 'STATUS_CLINIC_TIME_SLOT_SUCCESS',
    STATUS_CLINIC_TIME_SLOT_FAILURE     : 'STATUS_CLINIC_TIME_SLOT_FAILURE',

    // Reset State
    SLOT_RESET_STATE            : 'SLOT_RESET_STATE',
    DATE_SLOT_RESET_STATE       : 'DATE_SLOT_RESET_STATE',
    CLINIC_SLOT_RESET_STATE     : 'CLINIC_SLOT_RESET_STATE',
    FIRST_UNAUTHENTICATE  		: 'FIRST_UNAUTHENTICATE',
};
