/**
 * importConstants
 *
 * @subpackage             doctor Constants
 * @category               Constants
 * @DateOfCreation         22 May 2018
 * @ShortDescription       This is responsible for first Constants action names
 */
export const doctorConstants = {

    //SPECIALIZATION list
    SPECIALIZATION_FETCH_REQUEST     : 'SPECIALIZATION_FETCH_REQUEST',
    SPECIALIZATION_FETCH_SUCCESS     : 'SPECIALIZATION_FETCH_SUCCESS',
    SPECIALIZATION_FETCH_FAILURE     : 'SPECIALIZATION_FETCH_FAILURE',

    //DOCTOR_BY_SP list
    DOCTOR_BY_SP_FETCH_REQUEST     : 'DOCTOR_BY_SP_FETCH_REQUEST',
    DOCTOR_BY_SP_FETCH_SUCCESS     : 'DOCTOR_BY_SP_FETCH_SUCCESS',
    DOCTOR_BY_SP_FETCH_FAILURE     : 'DOCTOR_BY_SP_FETCH_FAILURE',

    //DOCTOR_BY_DETAIL list
    DOCTOR_BY_DETAIL_FETCH_REQUEST     : 'DOCTOR_BY_DETAIL_FETCH_REQUEST',
    DOCTOR_BY_DETAIL_FETCH_SUCCESS     : 'DOCTOR_BY_DETAIL_FETCH_SUCCESS',
    DOCTOR_BY_DETAIL_FETCH_FAILURE     : 'DOCTOR_BY_DETAIL_FETCH_FAILURE',

    //BOOK_APPOINTMENT_DOCTOR list
    BOOK_APPOINTMENT_DOCTOR_SAVE_REQUEST     : 'BOOK_APPOINTMENT_DOCTOR_SAVE_REQUEST',
    BOOK_APPOINTMENT_DOCTOR_SAVE_SUCCESS     : 'BOOK_APPOINTMENT_DOCTOR_SAVE_SUCCESS',
    BOOK_APPOINTMENT_DOCTOR_SAVE_FAILURE     : 'BOOK_APPOINTMENT_DOCTOR_SAVE_FAILURE',

    //MY_DOCTOR_APPOINTMENT
    MY_DOCTOR_APPOINTMENT_REQUEST     : 'MY_DOCTOR_APPOINTMENT_REQUEST',
    MY_DOCTOR_APPOINTMENT_SUCCESS     : 'MY_DOCTOR_APPOINTMENT_SUCCESS',
    MY_DOCTOR_APPOINTMENT_FAILURE     : 'MY_DOCTOR_APPOINTMENT_FAILURE',

    //CANCEL_MY_DOCTOR_APPOINTMENT
    CANCEL_MY_DOCTOR_APPOINTMENT_REQUEST     : 'CANCEL_MY_DOCTOR_APPOINTMENT_REQUEST',
    CANCEL_MY_DOCTOR_APPOINTMENT_SUCCESS     : 'CANCEL_MY_DOCTOR_APPOINTMENT_SUCCESS',
    CANCEL_MY_DOCTOR_APPOINTMENT_FAILURE     : 'CANCEL_MY_DOCTOR_APPOINTMENT_FAILURE',

    //DOCTOR_APPOINTMENT_LIST
    DOCTOR_APPOINTMENT_LIST_REQUEST     : 'DOCTOR_APPOINTMENT_LIST_REQUEST',
    DOCTOR_APPOINTMENT_LIST_SUCCESS     : 'DOCTOR_APPOINTMENT_LIST_SUCCESS',
    DOCTOR_APPOINTMENT_LIST_FAILURE     : 'DOCTOR_APPOINTMENT_LIST_FAILURE',

    //CANCEL_BY_DOCTOR_APPOINTMENT
    CANCEL_BY_DOCTOR_APPOINTMENT_REQUEST     : 'CANCEL_BY_DOCTOR_APPOINTMENT_REQUEST',
    CANCEL_BY_DOCTOR_APPOINTMENT_SUCCESS     : 'CANCEL_BY_DOCTOR_APPOINTMENT_SUCCESS',
    CANCEL_BY_DOCTOR_APPOINTMENT_FAILURE     : 'CANCEL_BY_DOCTOR_APPOINTMENT_FAILURE',

    //UPLOAD_SAVE
    UPLOAD_SAVE_REQUEST     : 'UPLOAD_SAVE_REQUEST',
    UPLOAD_SAVE_SUCCESS     : 'UPLOAD_SAVE_SUCCESS',
    UPLOAD_SAVE_FAILURE     : 'UPLOAD_SAVE_FAILURE',

    //COMPLETE_APPOINTMENT
    COMPLETE_APPOINTMENT_REQUEST     : 'COMPLETE_APPOINTMENT_REQUEST',
    COMPLETE_APPOINTMENT_SUCCESS     : 'COMPLETE_APPOINTMENT_SUCCESS',
    COMPLETE_APPOINTMENT_FAILURE     : 'COMPLETE_APPOINTMENT_FAILURE',

    //DOCTOR_REFERRAL
    DOCTOR_REFERRAL_REQUEST     : 'DOCTOR_REFERRAL_REQUEST',
    DOCTOR_REFERRAL_SUCCESS     : 'DOCTOR_REFERRAL_SUCCESS',
    DOCTOR_REFERRAL_FAILURE     : 'DOCTOR_REFERRAL_FAILURE',

    //DOCTOR_REFERRED
    DOCTOR_REFERRED_REQUEST     : 'DOCTOR_REFERRED_REQUEST',
    DOCTOR_REFERRED_SUCCESS     : 'DOCTOR_REFERRED_SUCCESS',
    DOCTOR_REFERRED_FAILURE     : 'DOCTOR_REFERRED_FAILURE',

    //REFERTO_DOCTOR
    REFERTO_DOCTOR_REQUEST     : 'REFERTO_DOCTOR_REQUEST',
    REFERTO_DOCTOR_SUCCESS     : 'REFERTO_DOCTOR_SUCCESS',
    REFERTO_DOCTOR_FAILURE     : 'REFERTO_DOCTOR_FAILURE',

    //NEW_PATIENT_BY_DOC
    NEW_PATIENT_BY_DOC_REQUEST     : 'NEW_PATIENT_BY_DOC_REQUEST',
    NEW_PATIENT_BY_DOC_SUCCESS     : 'NEW_PATIENT_BY_DOC_SUCCESS',
    NEW_PATIENT_BY_DOC_FAILURE     : 'NEW_PATIENT_BY_DOC_FAILURE',


    //FAVORITE_LIST
    FAVORITE_LIST_REQUEST     : 'FAVORITE_LIST_REQUEST',
    FAVORITE_LIST_SUCCESS     : 'FAVORITE_LIST_SUCCESS',
    FAVORITE_LIST_FAILURE     : 'FAVORITE_LIST_FAILURE',

    // Reset State
    FIRST_RESET_STATE     : 'FIRST_RESET_STATE',
    FIRST_UPDATE_STATE    : 'FIRST_UPDATE_STATE',
    FIRST_UNAUTHENTICATE  : 'FIRST_UNAUTHENTICATE',
};
