/**
 * loginConstants
 *
 * @subpackage             Login Constants
 * @category               Constants
 * @DateOfCreation         06 Dec 2018
 * @ShortDescription       This is responsible for Login Constants action names
 */
export const loginConstants = {
    
    LOGIN_REQUEST           : 'LOGIN_REQUEST',
    LOGIN_SUCCESS           : 'LOGIN_SUCCESS',
    LOGIN_FAILURE           : 'LOGIN_FAILURE',

    LOGOUT_SUCCESS          : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE          : 'LOGOUT_FAILURE',
    LOGIN_UPDATE_STATE      : 'LOGIN_UPDATE_STATE',

    REGISTRATION_V_REQUEST    : 'REGISTRATION_V_REQUEST',
    REGISTRATION_V_SUCCESS    : 'REGISTRATION_V_SUCCESS',
    REGISTRATION_V_FAILURE    : 'REGISTRATION_V_FAILURE',

    REGISTRATION_REQUEST    : 'REGISTRATION_REQUEST',
    REGISTRATION_SUCCESS    : 'REGISTRATION_SUCCESS',
    REGISTRATION_FAILURE    : 'REGISTRATION_FAILURE',

    REGISTRATION_D_REQUEST    : 'REGISTRATION_D_REQUEST',
    REGISTRATION_D_SUCCESS    : 'REGISTRATION_D_SUCCESS',
    REGISTRATION_D_FAILURE    : 'REGISTRATION_D_FAILURE',

    FORGOT_PASSWORD_REQUEST    : 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS    : 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE    : 'FORGOT_PASSWORD_FAILURE',

    RESET_PASSWORD_REQUEST    : 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS    : 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE    : 'RESET_PASSWORD_FAILURE'
};
