/**
 * importConstants
 *
 * @subpackage             fixture Constants
 * @category               Constants
 * @DateOfCreation         22 May 2018
 * @ShortDescription       This is responsible for first Constants action names
 */
export const medicalConstants = {

    //MEDICAL_STORE_List
    MEDICAL_STORE_FETCH_REQUEST     : 'MEDICAL_STORE_FETCH_REQUEST',
    MEDICAL_STORE_FETCH_SUCCESS     : 'MEDICAL_STORE_FETCH_SUCCESS',
    MEDICAL_STORE_FETCH_FAILURE     : 'MEDICAL_STORE_FETCH_FAILURE',

    //MEDICAL_STORE_DETAIL
    MEDICAL_STORE_DETAIL_FETCH_REQUEST     : 'MEDICAL_STORE_DETAIL_FETCH_REQUEST',
    MEDICAL_STORE_DETAIL_FETCH_SUCCESS     : 'MEDICAL_STORE_DETAIL_FETCH_SUCCESS',
    MEDICAL_STORE_DETAIL_FETCH_FAILURE     : 'MEDICAL_STORE_DETAIL_FETCH_FAILURE',

    //MEDICAL_STORE_UPCOMING
    MEDICAL_STORE_UPCOMING_FETCH_REQUEST     : 'MEDICAL_STORE_UPCOMING_FETCH_REQUEST',
    MEDICAL_STORE_UPCOMING_FETCH_SUCCESS     : 'MEDICAL_STORE_UPCOMING_FETCH_SUCCESS',
    MEDICAL_STORE_UPCOMING_FETCH_FAILURE     : 'MEDICAL_STORE_UPCOMING_FETCH_FAILURE',

    //BOOK_MEDICINE
    BOOK_MEDICINE_FETCH_REQUEST     : 'BOOK_MEDICINE_FETCH_REQUEST',
    BOOK_MEDICINE_FETCH_SUCCESS     : 'BOOK_MEDICINE_FETCH_SUCCESS',
    BOOK_MEDICINE_FETCH_FAILURE     : 'BOOK_MEDICINE_FETCH_FAILURE',

    //MY_BOOK_MEDICINE
    MY_BOOK_MEDICINE_FETCH_REQUEST     : 'MY_BOOK_MEDICINE_FETCH_REQUEST',
    MY_BOOK_MEDICINE_FETCH_SUCCESS     : 'MY_BOOK_MEDICINE_FETCH_SUCCESS',
    MY_BOOK_MEDICINE_FETCH_FAILURE     : 'MY_BOOK_MEDICINE_FETCH_FAILURE',

    //PATIENT_MEDICAL_ORDER
    PATIENT_MEDICAL_ORDER_FETCH_REQUEST     : 'PATIENT_MEDICAL_ORDER_FETCH_REQUEST',
    PATIENT_MEDICAL_ORDER_FETCH_SUCCESS     : 'PATIENT_MEDICAL_ORDER_FETCH_SUCCESS',
    PATIENT_MEDICAL_ORDER_FETCH_FAILURE     : 'PATIENT_MEDICAL_ORDER_FETCH_FAILURE',

    //ORDER_STATUS
    ORDER_STATUS_REQUEST     : 'ORDER_STATUS_REQUEST',
    ORDER_STATUS_SUCCESS     : 'ORDER_STATUS_SUCCESS',
    ORDER_STATUS_FAILURE     : 'ORDER_STATUS_FAILURE',

    // Reset State
    FIRST_RESET_STATE     : 'FIRST_RESET_STATE',
    FIRST_UPDATE_STATE    : 'FIRST_UPDATE_STATE',
    FIRST_UNAUTHENTICATE  : 'FIRST_UNAUTHENTICATE',
};
