/**
 * importConstants
 *
 * @subpackage             patient Constants
 * @category               Constants
 * @DateOfCreation         22 May 2018
 * @ShortDescription       This is responsible for first Constants action names
 */
export const patientConstants = {

    //patient detail
    PATIENT_HISTORY_FETCH_REQUEST     : 'PATIENT_HISTORY_FETCH_REQUEST',
    PATIENT_HISTORY_FETCH_SUCCESS     : 'PATIENT_HISTORY_FETCH_SUCCESS',
    PATIENT_HISTORY_FETCH_FAILURE     : 'PATIENT_HISTORY_FETCH_FAILURE',

    //PRESCRIPTION_LIST detail
    PRESCRIPTION_LIST_FETCH_REQUEST     : 'PRESCRIPTION_LIST_FETCH_REQUEST',
    PRESCRIPTION_LIST_FETCH_SUCCESS     : 'PRESCRIPTION_LIST_FETCH_SUCCESS',
    PRESCRIPTION_LIST_FETCH_FAILURE     : 'PRESCRIPTION_LIST_FETCH_FAILURE',

    //CANCEL_patient detail
    GET_MY_PATIENT_LIST_FETCH_REQUEST     : 'GET_MY_PATIENT_LIST_FETCH_REQUEST',
    GET_MY_PATIENT_LIST_FETCH_SUCCESS     : 'GET_MY_PATIENT_LIST_FETCH_SUCCESS',
    GET_MY_PATIENT_LIST_FETCH_FAILURE     : 'GET_MY_PATIENT_LIST_FETCH_FAILURE',

    //REFERRAL_DOCTOR_FETCH detail
    REFERRAL_DOCTOR_FETCH_REQUEST     : 'REFERRAL_DOCTOR_FETCH_REQUEST',
    REFERRAL_DOCTOR_FETCH_SUCCESS     : 'REFERRAL_DOCTOR_FETCH_SUCCESS',
    REFERRAL_DOCTOR_FETCH_FAILURE     : 'REFERRAL_DOCTOR_FETCH_FAILURE',

    //HEALTH_PROBLEM_FETCH detail
    HEALTH_PROBLEM_FETCH_REQUEST     : 'HEALTH_PROBLEM_FETCH_REQUEST',
    HEALTH_PROBLEM_FETCH_SUCCESS     : 'HEALTH_PROBLEM_FETCH_SUCCESS',
    HEALTH_PROBLEM_FETCH_FAILURE     : 'HEALTH_PROBLEM_FETCH_FAILURE',

    //GET_RECENT_DOCTOR detail
    GET_RECENT_DOCTOR_REQUEST     : 'GET_RECENT_DOCTOR_REQUEST',
    GET_RECENT_DOCTOR_SUCCESS     : 'GET_RECENT_DOCTOR_SUCCESS',
    GET_RECENT_DOCTOR_FAILURE     : 'GET_RECENT_DOCTOR_FAILURE',

    // Reset State
    FIRST_RESET_STATE     : 'FIRST_RESET_STATE',
    FIRST_UPDATE_STATE    : 'FIRST_UPDATE_STATE',
    FIRST_UNAUTHENTICATE  : 'FIRST_UNAUTHENTICATE',
};
