/**
 * importConstants
 *
 * @subpackage             fixture Constants
 * @category               Constants
 * @DateOfCreation         22 May 2018
 * @ShortDescription       This is responsible for first Constants action names
 */
export const productConstants = {

    //PRODUCTS
    PRODUCT_FETCH_REQUEST     : 'PRODUCT_FETCH_REQUEST',
    PRODUCT_FETCH_SUCCESS     : 'PRODUCT_FETCH_SUCCESS',
    PRODUCT_FETCH_FAILURE     : 'PRODUCT_FETCH_FAILURE',

    //PRODUCTS
    PRODUCTS_FETCH_REQUEST     : 'PRODUCTS_FETCH_REQUEST',
    PRODUCTS_FETCH_SUCCESS     : 'PRODUCTS_FETCH_SUCCESS',
    PRODUCTS_FETCH_FAILURE     : 'PRODUCTS_FETCH_FAILURE',

    //PRODUCT_CAT
    PRODUCT_CAT_FETCH_REQUEST     : 'PRODUCT_CAT_FETCH_REQUEST',
    PRODUCT_CAT_FETCH_SUCCESS     : 'PRODUCT_CAT_FETCH_SUCCESS',
    PRODUCT_CAT_FETCH_FAILURE     : 'PRODUCT_CAT_FETCH_FAILURE',


	//PRODUCT DETAIL
    PRODUCT_DETAIL_REQUEST     : 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_SUCCESS     : 'PRODUCT_DETAIL_SUCCESS',
    PRODUCT_DETAIL_FAILURE     : 'PRODUCT_DETAIL_FAILURE',

    //MY_PRODUCTS
    MY_PRODUCT_FETCH_REQUEST     : 'MY_PRODUCT_FETCH_REQUEST',
    MY_PRODUCT_FETCH_SUCCESS     : 'MY_PRODUCT_FETCH_SUCCESS',
    MY_PRODUCT_FETCH_FAILURE     : 'MY_PRODUCT_FETCH_FAILURE',

    // Reset State
    FIRST_RESET_STATE     : 'FIRST_RESET_STATE',
    FIRST_UPDATE_STATE    : 'FIRST_UPDATE_STATE',
    FIRST_UNAUTHENTICATE  : 'FIRST_UNAUTHENTICATE',
};