/**
 * profileConstants
 *
 * @subpackage             profile Constants
 * @category               Constants
 * @DateOfCreation         22 May 2018
 * @ShortDescription       This is responsible for first Constants action names
 */
export const profileConstants = {

    
    //PROFILE_SOS common
    PROFILE_SOS_REQUEST   : 'PROFILE_SOS_REQUEST',
    PROFILE_SOS_SUCCESS   : 'PROFILE_SOS_SUCCESS',
    PROFILE_SOS_FAILURE   : 'PROFILE_SOS_FAILURE',

    //PROFILE_PIC common
    PROFILE_PIC_REQUEST   : 'PROFILE_PIC_REQUEST',
    PROFILE_PIC_SUCCESS   : 'PROFILE_PIC_SUCCESS',
    PROFILE_PIC_FAILURE   : 'PROFILE_PIC_FAILURE',

    //GET_DOCTOR
    GET_DOCTOR_REQUEST   : 'GET_DOCTOR_REQUEST',
    GET_DOCTOR_SUCCESS   : 'GET_DOCTOR_SUCCESS',
    GET_DOCTOR_FAILURE   : 'GET_DOCTOR_FAILURE',

    //GET_PATIENT
    GET_PATIENT_REQUEST   : 'GET_PATIENT_REQUEST',
    GET_PATIENT_SUCCESS   : 'GET_PATIENT_SUCCESS',
    GET_PATIENT_FAILURE   : 'GET_PATIENT_FAILURE',

    //PROFILE_PATIENT
    PROFILE_PATIENT_REQUEST   : 'PROFILE_PATIENT_REQUEST',
    PROFILE_PATIENT_SUCCESS   : 'PROFILE_PATIENT_SUCCESS',
    PROFILE_PATIENT_FAILURE   : 'PROFILE_PATIENT_FAILURE',

    //COUNCIL_DOCTOR
    COUNCIL_DOCTOR_REQUEST   : 'COUNCIL_DOCTOR_REQUEST',
    COUNCIL_DOCTOR_SUCCESS   : 'COUNCIL_DOCTOR_SUCCESS',
    COUNCIL_DOCTOR_FAILURE   : 'COUNCIL_DOCTOR_FAILURE',

    //SEND_OTP
    SEND_OTP_REQUEST   : 'SEND_OTP_REQUEST',
    SEND_OTP_SUCCESS   : 'SEND_OTP_SUCCESS',
    SEND_OTP_FAILURE   : 'SEND_OTP_FAILURE',

    //VERIFY_OTP
    VERIFY_OTP_REQUEST   : 'VERIFY_OTP_REQUEST',
    VERIFY_OTP_SUCCESS   : 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAILURE   : 'VERIFY_OTP_FAILURE',

    //WALLET
    WALLET_REQUEST   : 'WALLET_REQUEST',
    WALLET_SUCCESS   : 'WALLET_SUCCESS',
    WALLET_FAILURE   : 'WALLET_FAILURE',

    //WALLET_HISTORY
    WALLET_HISTORY_REQUEST   : 'WALLET_HISTORY_REQUEST',
    WALLET_HISTORY_SUCCESS   : 'WALLET_HISTORY_SUCCESS',
    WALLET_HISTORY_FAILURE   : 'WALLET_HISTORY_FAILURE',

    //MEMBERS
    MEMBERS_REQUEST   : 'MEMBERS_REQUEST',
    MEMBERS_SUCCESS   : 'MEMBERS_SUCCESS',
    MEMBERS_FAILURE   : 'MEMBERS_FAILURE',
    
    //ADD_MEMBER
    ADD_MEMBER_REQUEST   : 'ADD_MEMBER_REQUEST',
    ADD_MEMBER_SUCCESS   : 'ADD_MEMBER_SUCCESS',
    ADD_MEMBER_FAILURE   : 'ADD_MEMBER_FAILURE',
    

    // Reset State
    PROFILE_RESET_STATE     : 'PROFILE_RESET_STATE',
    FIRST_UNAUTHENTICATE  : 'FIRST_UNAUTHENTICATE',
};
